param([string]$Python = ".\.venv\Scripts\python.exe")
$ErrorActionPreference="Stop"
$ExpectedBranch="phase5/knowledge-notes-resources"
$BaseCommit="f8f211a6109c43697b90c9a26bf13bd8d2fdb864"
function Stop-Gate{param([string]$Message);Write-Host "";Write-Host "==============================================";Write-Host " PHASE 5.6 UNIFIED INGESTION PIPELINE: BLOCKED";Write-Host "==============================================";Write-Host $Message;exit 1}
function Run-Step{param([string]$Label,[scriptblock]$Command);Write-Host "";Write-Host $Label;& $Command;if($LASTEXITCODE -ne 0){Stop-Gate "$Label failed with exit code $LASTEXITCODE."}}
if(Test-Path $Python){$PythonResolved=(Resolve-Path $Python).Path}else{$cmd=Get-Command $Python -ErrorAction SilentlyContinue;if($null -eq $cmd){Stop-Gate "Python not found"};$PythonResolved=$cmd.Source}
$branch=(git branch --show-current).Trim();if($branch -ne $ExpectedBranch){Stop-Gate "Expected $ExpectedBranch but found $branch"};$head=(git rev-parse HEAD).Trim();if($head -ne $BaseCommit){Stop-Gate "Expected uncommitted Phase 5.6 work on $BaseCommit but found $head"}
$allowed=@("personal_learning_assistant/ingestion/__init__.py","personal_learning_assistant/domain/ingestion_models.py","personal_learning_assistant/ingestion/extractors.py","personal_learning_assistant/ingestion/chunking.py","personal_learning_assistant/ingestion/source_resolver.py","personal_learning_assistant/repositories/sqlite/ingestion_repository.py","personal_learning_assistant/services/unified_ingestion_service.py","phase5_ingest_documents.py","tests/test_phase5_unified_ingestion.py","PHASE5_FIX6_UNIFIED_INGESTION_PIPELINE.md","phase5_fix6_gate.ps1")
$set=@{};foreach($x in $allowed){$set[$x]=$true;if(-not(Test-Path $x -PathType Leaf)){Stop-Gate "Missing $x"}}
foreach($line in @(git status --porcelain=v1 -uall)){if([string]::IsNullOrWhiteSpace($line)){continue};$p=$line.Substring(3).Trim().Replace("\","/");if($p.Contains(" -> ")){$p=$p.Split(" -> ")[-1]};if(-not $set.ContainsKey($p)){Stop-Gate "Out-of-scope change: $p"}}
if(-not(Test-Path ".\.phase4_authority.json" -PathType Leaf)){Stop-Gate "authority control missing"};if(-not(Test-Path ".\data\learning_assistant.db" -PathType Leaf)){Stop-Gate "production SQLite missing"}
$dbBefore=(Get-FileHash ".\data\learning_assistant.db" -Algorithm SHA256).Hash;$controlBefore=(Get-FileHash ".\.phase4_authority.json" -Algorithm SHA256).Hash;$legacy=@{};Get-ChildItem ".\data" -Filter "*.json" -File -ErrorAction SilentlyContinue|ForEach-Object{$legacy[$_.FullName]=(Get-FileHash $_.FullName -Algorithm SHA256).Hash};$sources=@{};if(Test-Path ".\knowledge\documents" -PathType Container){Get-ChildItem ".\knowledge\documents" -Recurse -File|ForEach-Object{$sources[$_.FullName]=(Get-FileHash $_.FullName -Algorithm SHA256).Hash}}
Run-Step "[1/9] Focused Phase 5.6 unified-ingestion tests" {& $PythonResolved -m pytest tests\test_phase5_unified_ingestion.py -q}
Run-Step "[2/9] REAL registered-document ingestion preview (read-only)" {& $PythonResolved .\phase5_ingest_documents.py --database .\data\learning_assistant.db --root "project-documents=.\knowledge\documents"}
Run-Step "[3/9] Phase 5.1-5.5 regressions" {& $PythonResolved -m pytest tests\test_phase5_knowledge_registry_foundation.py tests\test_phase5_document_source_scanner.py tests\test_phase5_obsidian_vault_registry.py tests\test_phase5_notes_studio_foundation.py tests\test_phase5_resources2_core.py -q}
Run-Step "[4/9] Phase 4 post-promotion regressions" {& $PythonResolved -m pytest tests\test_phase4_post_promotion_verification.py tests\test_phase4_structured_authority_routing.py tests\test_phase4_authority_promotion.py -q}
Run-Step "[5/9] Complete suite (promotion-aware)" {$legacyNode="tests/test_phase2_closure_architecture.py::test_phase2_root_has_no_production_learning_assistant_database";& $PythonResolved -m pytest -q --deselect $legacyNode;if($LASTEXITCODE -ne 0){exit $LASTEXITCODE};$temp=Join-Path([IO.Path]::GetTempPath())("p56_phase2_"+[guid]::NewGuid().ToString('N'));try{New-Item -ItemType Directory -Path(Join-Path $temp 'tests') -Force|Out-Null;Copy-Item '.\tests\test_phase2_closure_architecture.py' (Join-Path $temp 'tests\test_phase2_closure_architecture.py');& $PythonResolved -m pytest ((Join-Path $temp 'tests\test_phase2_closure_architecture.py')+'::test_phase2_root_has_no_production_learning_assistant_database') -q;if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}}
Run-Step "[6/9] Python compilation" {& $PythonResolved -m compileall -q personal_learning_assistant phase5_ingest_documents.py tests\test_phase5_unified_ingestion.py}
Run-Step "[7/9] Installed dependency consistency" {& $PythonResolved -m pip check}
Run-Step "[8/9] SQLite integrity/FK read-only" {& $PythonResolved -c "import sqlite3;c=sqlite3.connect('file:data/learning_assistant.db?mode=ro',uri=True);assert c.execute('PRAGMA integrity_check').fetchone()[0]=='ok';assert not c.execute('PRAGMA foreign_key_check').fetchall();c.close()"}
Write-Host "";Write-Host "[9/9] Git whitespace + production/source immutability";$staged=@(git diff --cached --name-only);if($staged.Count -ne 0){Stop-Gate 'Gate expects no staged changes'};try{git add --intent-to-add -- $allowed;git diff --check $BaseCommit --;if($LASTEXITCODE -ne 0){Stop-Gate 'git diff --check failed'}}finally{git reset --quiet -- $allowed 2>$null}
$dbAfter=(Get-FileHash ".\data\learning_assistant.db" -Algorithm SHA256).Hash;if($dbAfter -ne $dbBefore){Stop-Gate 'production SQLite changed'};$controlAfter=(Get-FileHash ".\.phase4_authority.json" -Algorithm SHA256).Hash;if($controlAfter -ne $controlBefore){Stop-Gate 'authority control changed'}
foreach($p in $legacy.Keys){if((Get-FileHash $p -Algorithm SHA256).Hash -ne $legacy[$p]){Stop-Gate "legacy JSON changed: $p"}}
if(Test-Path ".\knowledge\documents" -PathType Container){$after=@(Get-ChildItem ".\knowledge\documents" -Recurse -File);if($after.Count -ne $sources.Count){Stop-Gate 'knowledge source count changed'};foreach($f in $after){if(-not $sources.ContainsKey($f.FullName)){Stop-Gate 'new knowledge source appeared'};if((Get-FileHash $f.FullName -Algorithm SHA256).Hash -ne $sources[$f.FullName]){Stop-Gate "knowledge source changed: $($f.FullName)"}}}
$m=@(git diff --name-only $BaseCommit -- personal_learning_assistant/repositories/sqlite/migrations);if($m.Count -ne 0){Stop-Gate 'Phase 5.6 must not alter historical migrations'}
Write-Host "";Write-Host "============================================";Write-Host " PHASE 5.6 UNIFIED INGESTION PIPELINE: PASS";Write-Host "============================================";Write-Host "Verified:";Write-Host " - Markdown/text/SRT-VTT/PPTX/PDF adapters are versioned and deterministic";Write-Host " - chunks preserve page/section/slide/time provenance";Write-Host " - source SHA-256 must match registered content";Write-Host " - extraction states are pending/running/completed/failed";Write-Host " - old chunks remain historical; current extraction is explicit";Write-Host " - superseded index jobs become stale";Write-Host " - successful extraction creates retrieval_handoff + outbox";Write-Host " - no FTS, embeddings, semantic retrieval or RAG runs";Write-Host " - real preview performs zero writes";Write-Host " - no production/source bytes changed";Write-Host "";Write-Host "Phase 5.6 is ready for review and commit."
