param([string]$Python = ".\.venv\Scripts\python.exe")
$ErrorActionPreference="Stop"
$ExpectedBranch="phase5/knowledge-notes-resources"
$BaseCommit="09a00dff51fe7f4141d4740032142ada8568e491"
function Stop-Gate{param([string]$Message); Write-Host ""; Write-Host "============================================"; Write-Host " PHASE 5.4 NOTES STUDIO FOUNDATION: BLOCKED"; Write-Host "============================================"; Write-Host $Message; exit 1}
function Run-Step{param([string]$Label,[scriptblock]$Command); Write-Host ""; Write-Host $Label; & $Command; if($LASTEXITCODE -ne 0){Stop-Gate "$Label failed with exit code $LASTEXITCODE."}}
if(Test-Path $Python){$PythonResolved=(Resolve-Path $Python).Path}else{$cmd=Get-Command $Python -ErrorAction SilentlyContinue;if($null -eq $cmd){Stop-Gate "Python not found"};$PythonResolved=$cmd.Source}
$branch=(git branch --show-current).Trim(); if($branch -ne $ExpectedBranch){Stop-Gate "Expected $ExpectedBranch but found $branch"}
$head=(git rev-parse HEAD).Trim(); if($head -ne $BaseCommit){Stop-Gate "Expected uncommitted Phase 5.4 work on $BaseCommit but found $head"}
$allowed=@("personal_learning_assistant/domain/notes_studio_models.py","personal_learning_assistant/repositories/filesystem/markdown_note_store.py","personal_learning_assistant/repositories/sqlite/notes_studio_repository.py","personal_learning_assistant/services/notes_studio_service.py","personal_learning_assistant/services/legacy_note_reconciliation.py","tests/test_phase5_notes_studio_foundation.py","PHASE5_FIX4_NOTES_STUDIO_FOUNDATION.md","phase5_fix4_gate.ps1")
$set=@{}; foreach($x in $allowed){$set[$x]=$true;if(-not(Test-Path $x -PathType Leaf)){Stop-Gate "Missing $x"}}
foreach($line in @(git status --porcelain=v1 -uall)){if([string]::IsNullOrWhiteSpace($line)){continue};$p=$line.Substring(3).Trim().Replace("\","/");if($p.Contains(" -> ")){$p=$p.Split(" -> ")[-1]};if(-not $set.ContainsKey($p)){Stop-Gate "Out-of-scope change: $p"}}
if(-not(Test-Path ".\.phase4_authority.json" -PathType Leaf)){Stop-Gate "authority control missing"}; if(-not(Test-Path ".\data\learning_assistant.db" -PathType Leaf)){Stop-Gate "production SQLite missing"}
$dbBefore=(Get-FileHash ".\data\learning_assistant.db" -Algorithm SHA256).Hash;$controlBefore=(Get-FileHash ".\.phase4_authority.json" -Algorithm SHA256).Hash
$legacy=@{};Get-ChildItem ".\data" -Filter "*.json" -File -ErrorAction SilentlyContinue|ForEach-Object{$legacy[$_.FullName]=(Get-FileHash $_.FullName -Algorithm SHA256).Hash}
$vaultPath=(& $PythonResolved -c "from obsidian_integration import get_vault_path; print(get_vault_path() or '')").Trim();$vault=@{};if($vaultPath -and(Test-Path $vaultPath -PathType Container)){Get-ChildItem $vaultPath -Recurse -Filter "*.md" -File|ForEach-Object{$vault[$_.FullName]=(Get-FileHash $_.FullName -Algorithm SHA256).Hash}}
Run-Step "[1/8] Focused Phase 5.4 Notes Studio tests" {& $PythonResolved -m pytest tests\test_phase5_notes_studio_foundation.py -q}
Run-Step "[2/8] Phase 5.1-5.3 regressions" {& $PythonResolved -m pytest tests\test_phase5_knowledge_registry_foundation.py tests\test_phase5_document_source_scanner.py tests\test_phase5_obsidian_vault_registry.py -q}
Run-Step "[3/8] Phase 4 post-promotion regressions" {& $PythonResolved -m pytest tests\test_phase4_post_promotion_verification.py tests\test_phase4_structured_authority_routing.py tests\test_phase4_authority_promotion.py -q}
Run-Step "[4/8] Complete suite (promotion-aware)" {$legacyNode="tests/test_phase2_closure_architecture.py::test_phase2_root_has_no_production_learning_assistant_database";& $PythonResolved -m pytest -q --deselect $legacyNode;if($LASTEXITCODE -ne 0){exit $LASTEXITCODE};$temp=Join-Path([IO.Path]::GetTempPath())("p54_phase2_"+[guid]::NewGuid().ToString('N'));try{New-Item -ItemType Directory -Path(Join-Path $temp 'tests') -Force|Out-Null;Copy-Item '.\tests\test_phase2_closure_architecture.py' (Join-Path $temp 'tests\test_phase2_closure_architecture.py');& $PythonResolved -m pytest ((Join-Path $temp 'tests\test_phase2_closure_architecture.py')+'::test_phase2_root_has_no_production_learning_assistant_database') -q;if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}}finally{Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue}}
Run-Step "[5/8] Python compilation" {& $PythonResolved -m compileall -q personal_learning_assistant tests\test_phase5_notes_studio_foundation.py}
Run-Step "[6/8] Installed dependency consistency" {& $PythonResolved -m pip check}
Run-Step "[7/8] SQLite integrity/FK read-only" {& $PythonResolved -c "import sqlite3;c=sqlite3.connect('file:data/learning_assistant.db?mode=ro',uri=True);assert c.execute('PRAGMA integrity_check').fetchone()[0]=='ok';assert not c.execute('PRAGMA foreign_key_check').fetchall();c.close()"}
Write-Host "";Write-Host "[8/8] Git whitespace + production/vault immutability";$staged=@(git diff --cached --name-only);if($staged.Count -ne 0){Stop-Gate 'Gate expects no staged changes'};try{git add --intent-to-add -- $allowed;git diff --check $BaseCommit --;if($LASTEXITCODE -ne 0){Stop-Gate 'git diff --check failed'}}finally{git reset --quiet -- $allowed 2>$null}
if((Get-FileHash ".\data\learning_assistant.db" -Algorithm SHA256).Hash -ne $dbBefore){Stop-Gate 'production SQLite changed'};if((Get-FileHash ".\.phase4_authority.json" -Algorithm SHA256).Hash -ne $controlBefore){Stop-Gate 'authority control changed'}
foreach($p in $legacy.Keys){if((Get-FileHash $p -Algorithm SHA256).Hash -ne $legacy[$p]){Stop-Gate "legacy JSON changed: $p"}}
if($vaultPath -and(Test-Path $vaultPath -PathType Container)){$after=@(Get-ChildItem $vaultPath -Recurse -Filter '*.md' -File);if($after.Count -ne $vault.Count){Stop-Gate 'vault Markdown count changed'};foreach($f in $after){if(-not $vault.ContainsKey($f.FullName)){Stop-Gate 'new Markdown appeared'};if((Get-FileHash $f.FullName -Algorithm SHA256).Hash -ne $vault[$f.FullName]){Stop-Gate "Markdown changed: $($f.FullName)"}}}
$m=@(git diff --name-only $BaseCommit -- personal_learning_assistant/repositories/sqlite/migrations);if($m.Count -ne 0){Stop-Gate 'Phase 5.4 must not add/change migrations'}
Write-Host "";Write-Host "==========================================";Write-Host " PHASE 5.4 NOTES STUDIO FOUNDATION: PASS";Write-Host "==========================================";Write-Host "Verified:";Write-Host " - Markdown remains authoritative note body";Write-Host " - create/update use atomic write + expected-hash conflict protection";Write-Host " - pin/archive are metadata-only";Write-Host " - trash/restore use recoverable vault moves";Write-Host " - file-changing commands journal planned/file_applied/database_committed/completed";Write-Host " - note saves enqueue derived-work outbox events";Write-Host " - legacy notes reconciliation is preview-only";Write-Host " - no production SQLite, authority, legacy JSON or real Markdown bytes changed";Write-Host "";Write-Host "Phase 5.4 is ready for review and commit."
